dist: xenial
language: java
jdk: openjdk14
cache:
  directories:
  - "$HOME/.m2/repository"
env:
- CLI_VERSION=latest
matrix:
  include:
  - jdk: oraclejdk11
    # See https://github.com/travis-ci/travis-ci/issues/8667
    install: true
    before_script:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
      > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - "./cc-test-reporter before-build"
    script:
    - mvn clean jacoco:prepare-agent install jacoco:report
    after_script:
    - "./cc-test-reporter format-coverage -t jacoco ./target/jacoco_fixed_for_codeclimate.xml"
    - "./cc-test-reporter upload-coverage"
    after_success:
    - bash <(curl -s https://codecov.io/bash)
    deploy:
    - provider: bintray
      file: bintray_info_maven.JSON
      user: incplusplus
      key: "$bintray_key"
      skip_cleanup: true
      on:
        repo: IncPlusPlus/bigtoolbox-math
        branch: master
    - provider: releases
      api_key:
        secure: cLdjLxLzY4jT9arO/NTsLAF1uDkSB58q6n7gr4DL6pYd1mwM+dTlJdr0aOsFufriKd9onGXD471L9Bd0K01YmGOPg9ccGZyj8xxiylI0WatjuvS+fLPE26kRrdvBWv5u4qYTaYYjz1W59hjTiq8l9okaSpXBBp9hTLn3Ey0CtH9n7MZiDSHzJE2qjNzve/OQARRdSjYiLBU3PcGq4c5Zh3Vun1Jo9Yh8vFsaw7ps9voxEPWZxjAuNK10DKERNMK7m5Cm/sfHpv+E8wVXmC9sXdE9tUrqVwOWIEcD/GHq2xrJ82UuY1LMwl8x1XlrRDGw8I3vesv5qmqXl4406piSEza5NEtj/D9DElIVTkP09xos+CWBffDsv1IS9Gk5PKkfN4yZzfD1rhD4ifE/XbpVhWkFWr+k0KBLgiVWLwTFUnnijWmHGr/CeO63u9V5x/5zDsnrtbu2MjN/zt0XOl4WTZPCI8BJaikvWBxnVZ+Qyg0Qu80tYFOqJ+TBYwgoL9kOx2nwKi0eEKBCOZ3zJBKVTAKZpbRzMXFWG47/+zDRWJW67JxSuqlr/Gz0JkQJ4W4EiGH+hof5cfeVTszkdeMgYQT6wL6thRQn6zk+LWJuXmKX39SrbdDF8rGEVQEX9ldctze8KieAEL1dEcTxyT1/yAZFZNT61Bj6o0jdKOSKfXY=
      file_glob: true
      file: target/bigtoolbox-math-*.*.*.jar
      skip_cleanup: true
      prerelease: true
      on:
        repo: IncPlusPlus/bigtoolbox-math
        branch: master
        tags: true
  - jdk: openjdk11
    # See https://github.com/travis-ci/travis-ci/issues/8667
    install: true
    before_script:
    - 'curl -H ''Cache-Control: no-cache'' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh
      | sudo bash'
    script:
    - mvn clean install
    - fossa init
    - fossa analyze
